openapi: 3.2.0
info:
  description: Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
  title: Argo Workflows Sync Service API
  version: 3.6.0
servers:
- url: http://localhost:2746
- url: https://localhost:2746
security:
- BearerToken: []
tags:
- name: SyncService
paths:
  /api/v1/sync/{namespace}:
    post:
      tags:
      - SyncService
      operationId: SyncService_CreateSyncLimit
      parameters:
      - name: namespace
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sync.SyncLimitResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/grpc.gateway.runtime.Error'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sync.CreateSyncLimitRequest'
        required: true
      summary: Sync service create sync limit
      x-summary-source: derived
  /api/v1/sync/{namespace}/{key}:
    get:
      tags:
      - SyncService
      operationId: SyncService_GetSyncLimit
      parameters:
      - name: namespace
        in: path
        required: true
        schema:
          type: string
      - name: key
        in: path
        required: true
        schema:
          type: string
      - name: type
        in: query
        schema:
          type: string
          enum:
          - CONFIGMAP
          - DATABASE
          default: CONFIGMAP
      - name: cmName
        in: query
        schema:
          type: string
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sync.SyncLimitResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/grpc.gateway.runtime.Error'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      summary: Sync service get sync limit
      x-summary-source: derived
    put:
      tags:
      - SyncService
      operationId: SyncService_UpdateSyncLimit
      parameters:
      - name: namespace
        in: path
        required: true
        schema:
          type: string
      - name: key
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sync.SyncLimitResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/grpc.gateway.runtime.Error'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sync.UpdateSyncLimitRequest'
        required: true
      summary: Sync service update sync limit
      x-summary-source: derived
    delete:
      tags:
      - SyncService
      operationId: SyncService_DeleteSyncLimit
      parameters:
      - name: namespace
        in: path
        required: true
        schema:
          type: string
      - name: key
        in: path
        required: true
        schema:
          type: string
      - name: type
        in: query
        schema:
          type: string
          enum:
          - CONFIGMAP
          - DATABASE
          default: CONFIGMAP
      - name: cmName
        in: query
        schema:
          type: string
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sync.DeleteSyncLimitResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/grpc.gateway.runtime.Error'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      summary: Sync service delete sync limit
      x-summary-source: derived
components:
  schemas:
    sync.SyncLimitResponse:
      type: object
      properties:
        cmName:
          type: string
        key:
          type: string
        limit:
          type: integer
        namespace:
          type: string
        type:
          $ref: '#/components/schemas/sync.SyncConfigType'
    grpc.gateway.runtime.Error:
      type: object
      properties:
        code:
          type: integer
        details:
          type: array
          items:
            $ref: '#/components/schemas/google.protobuf.Any'
        error:
          type: string
        message:
          type: string
    sync.CreateSyncLimitRequest:
      type: object
      properties:
        cmName:
          type: string
        key:
          type: string
        limit:
          type: integer
        namespace:
          type: string
        type:
          $ref: '#/components/schemas/sync.SyncConfigType'
    sync.DeleteSyncLimitResponse:
      type: object
    sync.SyncConfigType:
      type: string
      default: CONFIGMAP
      enum:
      - CONFIGMAP
      - DATABASE
    sync.UpdateSyncLimitRequest:
      type: object
      properties:
        cmName:
          type: string
        key:
          type: string
        limit:
          type: integer
        namespace:
          type: string
        type:
          $ref: '#/components/schemas/sync.SyncConfigType'
    google.protobuf.Any:
      type: object
      properties:
        type_url:
          type: string
        value:
          type: string
          format: byte
  securitySchemes:
    BearerToken:
      type: apiKey
      in: header
      name: Authorization
      description: JWT Bearer token
