openapi: 3.2.0
info:
  description: Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
  title: Argo Workflows Artifact Service API
  version: 3.6.0
servers:
- url: http://localhost:2746
- url: https://localhost:2746
security:
- BearerToken: []
tags:
- name: ArtifactService
paths:
  /artifact-files/{namespace}/{idDiscriminator}/{id}/{nodeId}/{artifactDiscriminator}/{artifactName}:
    get:
      tags:
      - ArtifactService
      summary: Argo Workflows Get an Artifact
      operationId: ArtifactService_GetArtifactFile
      parameters:
      - name: namespace
        in: path
        required: true
        schema:
          type: string
      - name: idDiscriminator
        in: path
        required: true
        schema:
          type: string
          enum:
          - workflow
          - archived-workflows
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: nodeId
        in: path
        required: true
        schema:
          type: string
      - name: artifactName
        in: path
        required: true
        schema:
          type: string
      - name: artifactDiscriminator
        in: path
        required: true
        schema:
          type: string
          enum:
          - outputs
      responses:
        '200':
          description: An artifact file.
          content:
            application/json:
              schema:
                type: string
                format: binary
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/grpc.gateway.runtime.Error'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /artifacts-by-uid/{uid}/{nodeId}/{artifactName}:
    get:
      tags:
      - ArtifactService
      summary: Argo Workflows Get an Output Artifact by UID
      operationId: ArtifactService_GetOutputArtifactByUID
      parameters:
      - name: uid
        in: path
        required: true
        schema:
          type: string
      - name: nodeId
        in: path
        required: true
        schema:
          type: string
      - name: artifactName
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: An artifact file.
          content:
            application/json:
              schema:
                type: string
                format: binary
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/grpc.gateway.runtime.Error'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /artifacts/{namespace}/{name}/{nodeId}/{artifactName}:
    get:
      tags:
      - ArtifactService
      summary: Argo Workflows Get an Output Artifact
      operationId: ArtifactService_GetOutputArtifact
      parameters:
      - name: namespace
        in: path
        required: true
        schema:
          type: string
      - name: name
        in: path
        required: true
        schema:
          type: string
      - name: nodeId
        in: path
        required: true
        schema:
          type: string
      - name: artifactName
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: An artifact file.
          content:
            application/json:
              schema:
                type: string
                format: binary
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/grpc.gateway.runtime.Error'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /input-artifacts-by-uid/{uid}/{nodeId}/{artifactName}:
    get:
      tags:
      - ArtifactService
      summary: Argo Workflows Get an Input Artifact by UID
      operationId: ArtifactService_GetInputArtifactByUID
      parameters:
      - name: uid
        in: path
        required: true
        schema:
          type: string
      - name: nodeId
        in: path
        required: true
        schema:
          type: string
      - name: artifactName
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: An artifact file.
          content:
            application/json:
              schema:
                type: string
                format: binary
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/grpc.gateway.runtime.Error'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /input-artifacts/{namespace}/{name}/{nodeId}/{artifactName}:
    get:
      tags:
      - ArtifactService
      summary: Argo Workflows Get an Input Artifact
      operationId: ArtifactService_GetInputArtifact
      parameters:
      - name: namespace
        in: path
        required: true
        schema:
          type: string
      - name: name
        in: path
        required: true
        schema:
          type: string
      - name: nodeId
        in: path
        required: true
        schema:
          type: string
      - name: artifactName
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: An artifact file.
          content:
            application/json:
              schema:
                type: string
                format: binary
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/grpc.gateway.runtime.Error'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    grpc.gateway.runtime.Error:
      type: object
      properties:
        code:
          type: integer
        details:
          type: array
          items:
            $ref: '#/components/schemas/google.protobuf.Any'
        error:
          type: string
        message:
          type: string
    google.protobuf.Any:
      type: object
      properties:
        type_url:
          type: string
        value:
          type: string
          format: byte
  securitySchemes:
    BearerToken:
      type: apiKey
      in: header
      name: Authorization
      description: JWT Bearer token
